#!/usr/bin/env bash
# Replace .venv/bin/python{,3,3.12} with a wrapper script that forces
# arm64 execution via `arch -arm64` before calling the universal
# Python framework binary. Idempotent — run as many times as needed
# (e.g. after recreating the venv with `python -m venv .venv`).
#
# WHY THIS EXISTS
# ===============
# On Apple Silicon, the unsigned TradeSynchronizer.app bundle is
# sometimes started by launchd UNDER ROSETTA when launched from
# Finder / Launchpad / Dock (verified empirically: vmmap on the GUI
# PID showed `Code Type: X86-64 (translated)`). Once a process is
# Rosetta-translated, downstream `arch -arm64` wrappers in
# build_app.sh's launcher and ProxyController.start don't reliably
# flip the engine subprocess to arm64 either, because:
#
#   * .venv/bin/python is a symlink to the universal Python
#     framework (x86_64 + arm64 slices);
#   * `posix_spawn` then sometimes picks the x86_64 slice based on
#     opaque heuristics involving signing state and parent arch.
#
# Symptom: subprocess crashes with
#   ImportError: dlopen(.../_cffi_backend.cpython-312-darwin.so):
#   (mach-o file, but is an incompatible architecture
#    (have 'arm64', need 'x86_64'))
# every time the engine tries `from mitmproxy import http`.
#
# WHAT THIS SCRIPT DOES
# =====================
# 1. Saves the current resolved target of .venv/bin/python3.12 to
#    .venv/bin/python3.12.original-symlink so the original path is
#    recoverable.
# 2. Replaces python3.12 with a bash script that re-execs the
#    framework Python under `arch -arm64` on Apple Silicon (no-op
#    on Intel).
# 3. Re-creates python and python3 as symlinks to the new shim.
#
# After running this, every caller of .venv/bin/python — the GUI,
# the engine subprocess it spawns via subprocess.Popen, the test
# runner, the pre-commit hook — lands on arm64 by construction.
# The other arch -arm64 wrappers in this codebase (Info.plist's
# LSRequiresNativeExecution, the .app launcher, ProxyController)
# become belt-and-suspenders on top of this primary fix.
#
# RESTORING THE ORIGINAL VENV
# ===========================
# If you ever need to undo this:
#   cd .venv/bin
#   rm python python3 python3.12
#   mv python3.12.original-symlink python3.12
#   ln -s python3.12 python
#   ln -s python3.12 python3
# (or just recreate the venv from scratch with `python -m venv .venv`
# and `pip install -r requirements.txt` — then re-run this script.)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENV_BIN="$REPO_ROOT/.venv/bin"

if [ ! -d "$VENV_BIN" ]; then
    echo "✗ $VENV_BIN does not exist. Create the venv first:"
    echo "    cd $REPO_ROOT"
    echo "    python3 -m venv .venv"
    echo "    .venv/bin/pip install -r requirements.txt"
    exit 1
fi

# Resolve the original framework Python path. If the symlink has
# already been replaced by a previous run of this script, fall back
# to the saved .original-symlink file.
if [ -L "$VENV_BIN/python3.12" ]; then
    REAL_PYTHON="$(readlink -f "$VENV_BIN/python3.12")"
elif [ -L "$VENV_BIN/python3.12.original-symlink" ]; then
    REAL_PYTHON="$(readlink -f "$VENV_BIN/python3.12.original-symlink")"
elif [ -x "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12" ]; then
    # Last-ditch fallback to the standard install location.
    REAL_PYTHON="/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12"
else
    echo "✗ Cannot find the original framework Python to wrap."
    echo "  Expected one of:"
    echo "    * $VENV_BIN/python3.12 (symlink)"
    echo "    * $VENV_BIN/python3.12.original-symlink"
    echo "    * /Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12"
    exit 2
fi

echo "Using framework Python: $REAL_PYTHON"

# Back up the original symlink if not already done.
if [ -L "$VENV_BIN/python3.12" ] && [ ! -e "$VENV_BIN/python3.12.original-symlink" ]; then
    echo "Backing up original symlink → $VENV_BIN/python3.12.original-symlink"
    cp -P "$VENV_BIN/python3.12" "$VENV_BIN/python3.12.original-symlink"
fi

# Remove existing python entries so we can recreate them cleanly.
rm -f "$VENV_BIN/python3.12" "$VENV_BIN/python3" "$VENV_BIN/python"

# Write the arm64-forcing shim as python3.12.
cat > "$VENV_BIN/python3.12" <<EOF
#!/bin/bash
# Auto-generated by scripts/install-arm64-python-shim.sh — DO NOT EDIT BY HAND.
# Re-run that script to regenerate.
REAL_PYTHON="$REAL_PYTHON"
if [ "\$(uname -m)" = "arm64" ]; then
    exec /usr/bin/arch -arm64 "\$REAL_PYTHON" "\$@"
else
    exec "\$REAL_PYTHON" "\$@"
fi
EOF
chmod +x "$VENV_BIN/python3.12"

# Re-link the standard names.
ln -s python3.12 "$VENV_BIN/python3"
ln -s python3.12 "$VENV_BIN/python"

echo "✓ Installed arm64-forcing shim at:"
echo "    $VENV_BIN/python3.12"
echo "  with python + python3 symlinking to it."
echo
echo "Verification:"
"$VENV_BIN/python" -c "import platform; print('  arch =', platform.machine())"
"$VENV_BIN/python" -c "from mitmproxy import http; print('  mitmproxy import = OK')"
